[[plugins]]
  package = "netlify-plugin-flutter"

[plugins.inputs]
  # Optional: defaults to 'stable'
  channel = "stable"

[build]
  command = "flutter build web"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200